controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::login

app_auth_check_token:
    path: '/auth/check_token'
    controller: 'App\Controller\AuthController::checkToken'
    methods: ['POST']

app_auth_check_admin:
    path: '/auth/check_admin'
    controller: 'App\Controller\AuthController::checkAdmin'
    methods: ['POST']
